### ISSUE TITLE
Encounting AssertionError

### ISSUE THREAD

**Issue by xiaomingjie** [yifita/3PU#2]
HI @yifita 

When I tried to run ur code follow the README, I got an assertion error in line 92 [dense_interlevelplus.py](https://github.com/yifita/3PU/blob/master/code/dense_interlevelplus.py) . I print the list `skip_feature_xyz` and it looks like below

> [<tf.Tensor 'generator/case/If_0/level_1/concat_4:0' shape=(28, 312, 3) dtype=float32>]
> [<tf.Tensor 'generator/case/If_0/level_2/concat_4:0' shape=(28, 312, 3) dtype=float32>]
> [<tf.Tensor 'generator/case/If_0/level_3/concat_4:0' shape=(28, 312, 3) dtype=float32>]
> [<tf.Tensor 'generator/case/If_0/level_1/concat_4:0' shape=(28, 312, 3) dtype=float32>, <tf.Tensor 'generator/case/If_0/level_1_1/concat_4:0' shape=(28, 312, 3) dtype=float32>]

It seems that after recurrently calling the `body` function, something went wrong with the `skip_feature_xyz` whose length should be 1 according to ur code but it became 2. And then it went wrong.

Could u help me to fix this?

**Comment by yifita** [comment]
i suspect it's a corner case related to your input. Are you using the data we provide?
