### ISSUE TITLE
Train with custom data

### ISSUE THREAD

**Issue by dima74** [yifita/3PU#3]
Hello! May I ask for some details about training with my own data (as described [in this section](https://github.com/yifita/3PU#create-new-training-data)). 

I have dataset where each point cloud has 2048 points. And I want to train model to upsample from 512 points to 2048 points. As far as I understand I should change [these lines](https://github.com/yifita/3PU/blob/da9d178aa34d301c13c8774de5068386ede74b1a/prepare_data/create_tfrecords.py#L36-L41) to directories with my point clouds. But I have only one directory (with point clouds of size 2048).

**Comment by yifita** [comment]
Hi, you need to create 512 input points, we used poisson disc sampling to do so.
After that you'll have two folders for 512 and 2048 points respectively. Change L35 to a list including these two folders and L41 to [512, 2048] points. 
Then you should be good to go.
