### ISSUE TITLE
Can you please provide the .xyz file of Figure 11 in your paper ?

### ISSUE THREAD

**Issue by jialancong** [yifita/3PU#7]
I don't know the name of point cloud in your paper , which makes me hard to find it. Thank you !

**Comment by yifita** [comment]
They are cupid, damme and gramme.

**Comment by jialancong** [comment]
> They are cupid, damme and gramme.

Thank you very much！ But I still can't find them. Can you provide the dataset link of figure 11 and figure 12 ?

**Comment by yifita** [comment]
The training and test data are linked here https://github.com/yifita/3PU#input-points

After unzipping, you'll find the point files of the said models in different densities.

**Comment by jialancong** [comment]
> The training and test data are linked here https://github.com/yifita/3PU#input-points
> 
> After unzipping, you'll find the point files of the said models in different densities.

Got it！ Thank you very much !
